<a href="https://colab.research.google.com/github/AndreyGolovin85/Andrey/blob/master/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Для выполнения практической работы будет использоваться датасет, находящийся по ссылке: https://archive.ics.uci.edu/ml/datasets/spambase

Данный датасет состоит из 57 атрибутов:
Последний столбец "spambase.data" указывает, считалось ли электронное письмо спамом (1) или нет (0), то есть незапрошенной коммерческой электронной почтой. Большинство атрибутов указывают на то, часто ли встречалось в письме то или иное слово или символ. Атрибуты run-length (55-57) измеряют длину последовательностей последовательных заглавных букв.
Вот определения атрибутов:

48 непрерывных вещественных [0,100] атрибутов типа word_freq_WORD
= процент слов в электронном письме, которые соответствуют СЛОВУ, то есть 100 * (количество раз, когда СЛОВО появляется в электронном письме) / общее количество слов в электронном письме. "Слово" в данном случае-это любая строка буквенно-цифровых символов, ограниченная не буквенно-цифровыми символами или концом строки.

6 непрерывные реальные [0,100] атрибуты типа char_freq_CHAR]
= процент символов в электронном письме, соответствующих CHAR, т. е. 100 * (количество встреч СИМВОЛОВ) / общее количество символов в электронном письме

1 непрерывный реальный [1,...] атрибут типа capital_run_length_average
= средняя длина непрерывных последовательностей заглавных букв

1 непрерывное целое [1,...] атрибут типа capital_run_length_longest
= длина самой длинной непрерывной последовательности заглавных букв

1 непрерывное целое [1,...] атрибут типа capital_run_length_total
= сумма длины непрерывных последовательностей прописных букв
= общее количество заглавных букв в сообщении электронной почты

1 номинальное {0,1} Class атрибут типа спам
= обозначает, является ли электронная почта считалась спам (1) или нет (0), т. е. нежелательной коммерческой электронной почты.

Количество записей в датасете – 4600 шт. 
Пропущенные значения – Присутствуют.
Категориальные атрибуты – отсутствуют.

In [47]:
# Импортируем библиотеки.
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/gdrive')
 
data = pd.read_csv('/content/gdrive/MyDrive/spambase.data')
data

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


0  0.64  0.64.1  0.1  0.32   0.2  ...   0.43   0.44  3.756   61   278  1
0     0.21  0.28    0.50  0.0  0.14  0.28  ...  0.180  0.048  5.114  101  1028  1
1     0.06  0.00    0.71  0.0  1.23  0.19  ...  0.184  0.010  9.821  485  2259  1
2     0.00  0.00    0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191  1
3     0.00  0.00    0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191  1
4     0.00  0.00    0.00  0.0  1.85  0.00  ...  0.000  0.000  3.000   15    54  1
...    ...   ...     ...  ...   ...   ...  ...    ...    ...    ...  ...   ... ..
4595  0.31  0.00    0.62  0.0  0.00  0.31  ...  0.000  0.000  1.142    3    88  0
4596  0.00  0.00    0.00  0.0  0.00  0.00  ...  0.000  0.000  1.555    4    14  0
4597  0.30  0.00    0.30  0.0  0.00  0.00  ...  0.000  0.000  1.404    6   118  0
4598  0.96  0.00    0.00  0.0  0.32  0.00  ...  0.000  0.000  1.147    5    78  0
4599  0.00  0.00    0.65  0.0  0.00  0.00  ...  0.000  0.000  1.250    5    40  0

[4600 rows x 58 columns]

In [48]:
# Выводим типы данных для каждого признака
data.dtypes

0         float64
0.64      float64
0.64.1    float64
0.1       float64
0.32      float64
0.2       float64
0.3       float64
0.4       float64
0.5       float64
0.6       float64
0.7       float64
0.64.2    float64
0.8       float64
0.9       float64
0.10      float64
0.32.1    float64
0.11      float64
1.29      float64
1.93      float64
0.12      float64
0.96      float64
0.13      float64
0.14      float64
0.15      float64
0.16      float64
0.17      float64
0.18      float64
0.19      float64
0.20      float64
0.21      float64
0.22      float64
0.23      float64
0.24      float64
0.25      float64
0.26      float64
0.27      float64
0.28      float64
0.29      float64
0.30      float64
0.31      float64
0.32.2    float64
0.33      float64
0.34      float64
0.35      float64
0.36      float64
0.37      float64
0.38      float64
0.39      float64
0.40      float64
0.41      float64
0.42      float64
0.778     float64
0.43      float64
0.44      float64
3.756     float64
61        

In [49]:
# Выводим размер датафрейма.
data.shape

(4600, 58)

In [50]:
data.size

266800

In [51]:
# Выявлям пропуски в таблице data методом isnull()
data.isna().sum()

0         0
0.64      0
0.64.1    0
0.1       0
0.32      0
0.2       0
0.3       0
0.4       0
0.5       0
0.6       0
0.7       0
0.64.2    0
0.8       0
0.9       0
0.10      0
0.32.1    0
0.11      0
1.29      0
1.93      0
0.12      0
0.96      0
0.13      0
0.14      0
0.15      0
0.16      0
0.17      0
0.18      0
0.19      0
0.20      0
0.21      0
0.22      0
0.23      0
0.24      0
0.25      0
0.26      0
0.27      0
0.28      0
0.29      0
0.30      0
0.31      0
0.32.2    0
0.33      0
0.34      0
0.35      0
0.36      0
0.37      0
0.38      0
0.39      0
0.40      0
0.41      0
0.42      0
0.778     0
0.43      0
0.44      0
3.756     0
61        0
278       0
1         0
dtype: int64

Как видим в нашей выборке отсутствуют пропуски.

In [52]:
# Переименуем столбец '1' в 'spam' для удобства дальнейшего использования.
data = data.rename(columns={'1': 'spam'})
data

0  0.64  0.64.1  0.1  0.32   0.2  ...   0.43   0.44  3.756   61   278  spam
0     0.21  0.28    0.50  0.0  0.14  0.28  ...  0.180  0.048  5.114  101  1028     1
1     0.06  0.00    0.71  0.0  1.23  0.19  ...  0.184  0.010  9.821  485  2259     1
2     0.00  0.00    0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191     1
3     0.00  0.00    0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191     1
4     0.00  0.00    0.00  0.0  1.85  0.00  ...  0.000  0.000  3.000   15    54     1
...    ...   ...     ...  ...   ...   ...  ...    ...    ...    ...  ...   ...   ...
4595  0.31  0.00    0.62  0.0  0.00  0.31  ...  0.000  0.000  1.142    3    88     0
4596  0.00  0.00    0.00  0.0  0.00  0.00  ...  0.000  0.000  1.555    4    14     0
4597  0.30  0.00    0.30  0.0  0.00  0.00  ...  0.000  0.000  1.404    6   118     0
4598  0.96  0.00    0.00  0.0  0.32  0.00  ...  0.000  0.000  1.147    5    78     0
4599  0.00  0.00    0.65  0.0  0.00  0.00  ...  0.000  0.000  1.250    5    40     0

[4600 rows x 58 columns]

In [53]:
X = data.drop(columns=['spam'])
y = data.spam
 
# Разделим набор данных на обучающую и тестовую выборку в соотношении 70% на 30%.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

Выберем модель для обучения GradientBoostingClassifier и запустим
процесс обучения.

In [54]:
from sklearn.ensemble import GradientBoostingClassifier
gradient_boosting = GradientBoostingClassifier(learning_rate=0.1,
                                               n_estimators=100, max_depth=3, 
                                               random_state=None, ccp_alpha=0.0)
gradient_boosting.fit(X_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Выведем параметры точности обученной модели:

In [55]:
%%time
# Выведем основные параметры точности обученной модели.
from sklearn.metrics import confusion_matrix, classification_report
y_pred_gradient = gradient_boosting.predict(X_test)
confmat_gradient = confusion_matrix(y_true=y_test, y_pred=y_pred_gradient)

print(confmat_gradient)
print("Classification Report GradientBoosting")
print(classification_report(y_test, y_pred_gradient))

[[803  36]
 [ 44 497]]
Classification Report GradientBoosting
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       839
           1       0.93      0.92      0.93       541

    accuracy                           0.94      1380
   macro avg       0.94      0.94      0.94      1380
weighted avg       0.94      0.94      0.94      1380

CPU times: user 13.3 ms, sys: 0 ns, total: 13.3 ms
Wall time: 13.6 ms


Выберем модель для обучения RigeClassifier и запустим процесс обучения.

In [56]:
from sklearn.linear_model import RidgeClassifier
clf = RidgeClassifier(alpha=1.0, fit_intercept=True, normalize=False,
                      copy_X=True, max_iter=None, tol=0.001,
                      class_weight=None, solver='auto', random_state=None)
clf.fit(X_train, y_train)

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize=False, random_state=None,
                solver='auto', tol=0.001)

Выведем параметры точности обученной модели:

In [57]:
%%time
y_pred_clf = clf.predict(X_test)
confmat_clf = confusion_matrix(y_true=y_test,
y_pred=y_pred_clf)
print(confmat_clf)
print("Classification Report RidgeClassifier")
print(classification_report(y_test, y_pred_clf))

[[799  40]
 [116 425]]
Classification Report RidgeClassifier
              precision    recall  f1-score   support

           0       0.87      0.95      0.91       839
           1       0.91      0.79      0.84       541

    accuracy                           0.89      1380
   macro avg       0.89      0.87      0.88      1380
weighted avg       0.89      0.89      0.89      1380

CPU times: user 15.5 ms, sys: 14.5 ms, total: 30 ms
Wall time: 20.9 ms


Выберем модель для обучения PassiveAggressiveClassifier и запустим процесс обучения.

In [58]:
from sklearn.linear_model import PassiveAggressiveClassifier
clf_pa = PassiveAggressiveClassifier()
clf_pa.fit(X_train, y_train)

PassiveAggressiveClassifier(C=1.0, average=False, class_weight=None,
                            early_stopping=False, fit_intercept=True,
                            loss='hinge', max_iter=1000, n_iter_no_change=5,
                            n_jobs=None, random_state=None, shuffle=True,
                            tol=0.001, validation_fraction=0.1, verbose=0,
                            warm_start=False)

Выведем параметры точности обученной модели:

In [59]:
%%time
y_pred_clf_pa = clf_pa.predict(X_test)
confmat_clf_pa = confusion_matrix(y_true=y_test,
y_pred=y_pred_clf_pa)
print(confmat_clf_pa)
print("Classification Report PassiveAggressive")
print(classification_report(y_test, y_pred_clf_pa))

[[576 263]
 [ 14 527]]
Classification Report PassiveAggressive
              precision    recall  f1-score   support

           0       0.98      0.69      0.81       839
           1       0.67      0.97      0.79       541

    accuracy                           0.80      1380
   macro avg       0.82      0.83      0.80      1380
weighted avg       0.86      0.80      0.80      1380

CPU times: user 16.5 ms, sys: 19.5 ms, total: 36 ms
Wall time: 19.2 ms


Вывод. Как видно из отчетов Classification Report GradientBoosting, Classification Report RidgeClassifier, Classification Report PassiveAggressive, наилучшие точностные показатели обеспечивает классификатор, построенный на основе GradientBoostingClassifier.